apiVersion: v1
kind: Service
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sa-logic