version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8
  build:
    commands:
      - java -version
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/csye7220app-0.0.1-SNAPSHOT.war
  discard-paths: yes
