apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
        - image: adikelkar4/sentiment-analysis-frontend
          imagePullPolicy: Always
          name: sa-frontend
          ports:
          - containerPort: 80