apiVersion: v1
kind: Service
metadata:
  name: sa-webapp
  labels:
    app: sa-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-webapp